name: Animal Farm Node.js CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.18"
            - name: Install dependencies
              run: npm install
            - name: Build production
              run: npm run build --if-present
            - name: Run tests
              run: npm run test --if-present
